#!/usr/bin/python3

# XXX TODO translation
# We need automated translations for this tool.
# This implies we need to actually parse the Markdown
# of each rule, so we avoid running a translator
# against the code blocks. The trickiest part
# is avoiding inline code blocks inside a sentence,
# so we will probably have to run the whole thing
# against the translator and then replace the
# translated code blocks with the original content,
# to avoid translating sentence fragments that may
# lose the meaning of the entire sentence.

import fnmatch
import json
import jsonschema
import os
import os.path
import re
import subprocess
import yaml

# JSON schema for templates.
SCHEMA_TEMPLATE = {
    "type": "object",
    "properties": {
        "summary": {"type": "string", "pattern": "^[^\\r\\n]*$"},
        "references": {
            "type": "array",
            "items": {"type": "string", "pattern": "^https?://"},
        },
        "taxonomy": {"type": "array", "items": {"type": "string", "minLength": 3}},
    },
    "additionalProperties": {"type": "string"},
    "required": ["title", "summary", "description", "recommendations", "details"],
}

# Regular expressions used to parse the rule text.
re_title = re.compile(r"^## (.+)$")
re_link = re.compile(r"\((https?://[^\)]+)\)")

# Download the latest version of the Bearer rules.
if not os.path.exists("./bearer-rules/rules/"):
    print("git clone https://github.com/Bearer/bearer-rules.git")
    subprocess.run(
        ["git", "clone", "https://github.com/Bearer/bearer-rules.git"], check=True
    )
else:
    print("git pull")
    subprocess.run(["git", "pull"], cwd=os.path.abspath("./bearer-rules/"), check=True)
print()

# Parse the rules. We only care for the metadata, discard the rest.
for root, dirs, files in os.walk("./bearer-rules/rules/"):
    if "/shared/" in root:
        continue
    for name in fnmatch.filter(files, "*.yml"):
        pathname = os.path.join(root, name)
        print("<== " + pathname)
        with open(pathname, "r") as fd:
            raw = fd.read()
        rule = yaml.safe_load(raw)["metadata"]

        # Construct a template object based on the metadata.
        sections = {}
        current = None
        for line in rule["remediation_message"].split("\n"):
            m = re_title.match(line)
            if m is not None:
                current = m.groups(1)[0]
                sections[current] = [""]
            else:
                assert current is not None
                sections[current].append(line)
        if "Resources" in sections:
            resources = sections.pop("Resources")
        else:
            resources = []
        for current in sections:
            sections[current] = "\n".join(x for x in sections[current])
        references = [rule["documentation_url"]]
        if resources:
            for line in resources:
                if not line:
                    continue
                m = re_link.search(line)
                if not m:
                    continue
                references.append(m.groups(1)[0])
        description = sections.get("Description", "")
        recommendations = sections.get("Remediations", "")
        if "\n\n" in description:
            summary = description[: description.find("\n\n")]
            if "\n" in summary:
                summary = summary.replace("\n", " ")
        if "\n" in description:
            summary = description[: description.find("\n")]
            if not summary.endswith("."):
                summary = description.replace("\n", " ")
        else:
            summary = "{% include 'description' %}"
        taxonomy = ["CWE-%d" % x for x in rule["cwe_id"]]
        template_name = rule["id"]
        template = {
            "title": rule["description"],
            "summary": summary,
            "description": description,
            "recommendations": recommendations,
            "taxonomy": taxonomy,
            "references": references,
            "details": "{% include '../generic_bandit_issue/details' %}",
        }

        # Make sure we generated a valid template.
        jsonschema.validate(template, SCHEMA_TEMPLATE)

        # Output the template file.
        outfile = "../" + template_name + ".json5"
        print("==> " + outfile)
        with open(outfile, "w") as fd:
            fd.write(
                "// This file was autogenerated by: %s\n// Do not edit!!!\n"
                % os.path.basename(__file__)
            )
            json.dump(template, fd)
        try:
            os.unlink("../" + template_name + ".schema.json")
        except OSError:
            pass
        try:
            os.unlink("../" + template_name + ".py")
        except OSError:
            pass
        os.symlink(
            "../generic_source_code_issue.schema.json",
            "../" + template_name + ".schema.json",
        )
        os.symlink("../generic_source_code_issue.py", "../" + template_name + ".py")
