#!/usr/bin/python3

import io
import re
import csv
import sys
import json
import os.path
import traceback
from datetime import datetime

from lxml import etree
from lxml.objectify import deannotate

# TODO get the severity of the issue from the CVEs, maybe even provide info from CVE too

# Set to True to include informational issues found by Nikto in the report.
INCLUDE_INFO = False
# INCLUDE_INFO = True

# Load the OSVDB to CVE map.
osvdb2cve = {}
try:
    with open(os.path.join(os.path.dirname(__file__), "osvdb2cve.json")) as fd:
        osvdb2cve = json.load(fd)
    del fd
except Exception:
    traceback.print_exc()


# https://stackoverflow.com/a/71886208/426293
def remove_namespaces(root):
    for elem in root.getiterator():
        if not (
            isinstance(elem, etree._Comment)
            or isinstance(elem, etree._ProcessingInstruction)
        ):
            localname = etree.QName(elem).localname
            if elem.tag != localname:
                elem.tag = etree.QName(elem).localname
            for attr_name in elem.attrib:
                local_attr_name = etree.QName(attr_name).localname
                if attr_name != local_attr_name:
                    attr_value = elem.attrib[attr_name]
                    del elem.attrib[attr_name]
                    elem.attrib[local_attr_name] = attr_value
    deannotate(root, cleanup_namespaces=True)


# Entry point.
def main():
    # Load the input file in memory all at once.
    # Not ideal, but it's the easiest way to parse it without knowing the format beforehand.
    input_data = sys.stdin.read()

    # Trivial case: the file is empty.
    if not input_data:
        sys.stderr.write("Empty file received, surely this is an error?\n")
        json.dump([], sys.stdout)
        return

    # If it's an XML file, we can expect an XML header to be in the first line.
    if input_data.startswith('<?xml version="1.0" ?>'):
        output = parse_nikto_xml(input_data)

    # If it's a CSV file, we can expect the first line to be the Nikto version,
    # and the second line to contain the target host and port.
    elif re.match('"Nikto - v.*"\\n', input_data):
        output = parse_nikto_csv(input_data)

    # If we got here, we were sent the wrong file type.
    else:
        sys.stderr.write(
            "Invalid file type, are you sure this was generated by nikto.pl?\n"
        )
        output = []

    # Convert the output array to JSON and send it over stdout.
    json.dump(output, sys.stdout)


def parse_nikto_xml(input_data):
    # We will report a single issue object with all findings.
    issue = {
        "tools": ["nikto"],
        "template": "multiple_nikto_issues",
        "severity": "high",
        "affects": [],
        "taxonomy": [],
        "references": [],
        "issues": {},
    }

    # Parse the XML file.
    root = etree.fromstring(input_data)
    remove_namespaces(root)

    # The root element should always be the <niktoscan> tag.
    # Get the command line options from here.
    # Do not get the start and end times from here, they are unreliable.
    niktoscan = root
    assert niktoscan.tag == "niktoscan", niktoscan.tag
    assert niktoscan.attrib["nxmlversion"] == "1.2", niktoscan.attrib["nxmlversion"]

    # The first and only child should always be the <scandetails> tag.
    # Get the target host and the start time of the scan here.
    children = root.getchildren()
    assert len(children) == 1, len(children)
    scandetails = children[0]
    assert scandetails.tag == "scandetails", scandetails.tag
    starttime = scandetails.attrib.get("starttime")
    if starttime:
        try:
            ut = datetime.strptime(starttime, "%Y-%m-%d %H:%M:%S")
            issue["_start"] = ut
        except Exception:
            pass
    targethostname = scandetails.attrib.get("targethostname")
    targetip = scandetails.attrib.get("targetip")
    targetport = scandetails.attrib.get("targetport")
    use_ssl = targetport == "443"
    if not targetport:
        targetport = "443" if use_ssl else "80"
    baseurl = "%s://%s:%s" % (
        "https" if use_ssl else "http",
        targethostname if targethostname else targetip,
        targetport,
    )

    # The remaining children are <item> tags with each finding,
    # up until the last tag <statistics>.
    collected = []
    for child in scandetails.getchildren():
        # We found a vulnerability.
        if child.tag == "item":
            item = child

            # Skip if the item is just informational.
            osvdblink = item.attrib["osvdblink"]
            assert osvdblink.startswith("http://osvdb.org/")
            osvdb = "OSVDB-" + osvdblink[17:]
            if osvdb == "OSVDB-0" and not INCLUDE_INFO:
                continue

            # Convert the OSVDB to CVE.
            try:
                cvelist = osvdb2cve.get(osvdb, [osvdb])
                if not cvelist:
                    cvelist = [osvdb]
            except Exception:
                cvelist = [osvdb]
            issue["taxonomy"].extend(cvelist)

            # Get the description of the issue.
            description = item.find("description").text

            # Get the affected path.
            if targethostname:
                namelink = item.find("namelink").text
                assert namelink.startswith(baseurl)
                affects = namelink
            else:
                iplink = item.find("iplink").text
                assert iplink.startswith(baseurl)
                affects = iplink
            issue["affects"].append(affects)
            path = affects[len(baseurl) :]

            # Add the issue to the list of collected issues.
            found = (path, cvelist, description)
            if found not in collected:
                collected.append(found)

    # Return an empty list if we found nothing.
    if not collected:
        return []

    # Add the collected issues to the issue object.
    issue["issues"] = {
        baseurl: [
            {
                "path": x[0],
                "cve": x[1],
                "msg": x[2],
            }
            for x in collected
        ]
    }

    # Clean up the issue object and return it.
    issue["affects"] = sorted(set(issue["affects"]))
    issue["taxonomy"] = sorted(set(issue["taxonomy"]))
    issue["references"] = sorted(set(issue["references"]))
    assert issue["affects"], issue
    if not issue["taxonomy"]:
        del issue["taxonomy"]
    if not issue["references"]:
        del issue["references"]
    return [issue]


def parse_nikto_csv(input_data):
    # Convert the input string to a pseudo-file.
    fd = io.StringIO(input_data)

    # Read the first line and discard it.
    fd.readline()

    # Pass the pseudo-file to the CSV parser.
    reader = csv.reader(fd)

    # Read the second line and get the host and port.
    try:
        row = next(reader)
    except StopIteration:
        return []  # EOF due to empty scan
    hostname = row[0]
    ipv4 = row[1]
    port = row[2]
    hostname = hostname or ipv4

    # Keep all of the issues found here.
    issues = []

    # Nikto, sadly, does not preserve its command line in CSV files.
    # We can only guess if SSL was used or not.
    if port == 443:
        cmdline = ["nikto.pl", "-host", hostname, "-port", port, "-ssl"]
        use_ssl = True
    else:
        cmdline = ["nikto.pl", "-host", hostname, "-port", port]
        use_ssl = False

    # The rest of the lines contain the vulnerabilities.
    for row in reader:
        # The OSVDB-0 ID is used to informational lines. We can ignore those.
        osvdb = row[2]
        if osvdb == "OSVDB-0" and not INCLUDE_INFO:
            continue

        # Get the affected URI.
        path = row[4]

        # Convert the OSVDB to CVE.
        cvelist = osvdb2cve.get(osvdb, [osvdb])

        # Get the message.
        msg = row[5]

        # Add the issue to the list.
        item = (path, cvelist, msg)
        if item not in issues:
            issues.append(item)

    # If we didn't find any actual issues, just return an empty array.
    if not issues:
        return []

    # Return an issue object.
    issues.sort()
    taxonomy = []
    for x in issues:
        taxonomy.extend(x[1])
    return [
        {
            "tools": ["nikto"],
            "template": "nikto",
            "severity": "high",
            "cmdline": cmdline,
            "affects": sorted(
                set(
                    "%s://%s:%s%s"
                    % ("https" if use_ssl else "http", hostname, port, x[0])
                    for x in issues
                )
            ),
            "taxonomy": sorted(set(taxonomy)),
            "issues": {
                ("%s://%s:%s" % ("https" if use_ssl else "http", hostname, port)): [
                    {
                        "path": x[0],
                        "cve": x[1],
                        "msg": x[2],
                    }
                    for x in issues
                ],
            },
        }
    ]


if __name__ == "__main__":
    main()
